import type { Metadata } from "next";
import Sidebar from "@/src/components/dashboard/Sidebar";
import Header from "@/src/components/dashboard/Header";
import Link from "next/link";
import Image from "next/image";
import logoPng from "@/public/static/icons/logo.png";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/static/icons/logo.svg",
  },
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen">
      <aside className="flex h-full w-52 flex-col gap-6 border-r px-4 py-6">
        <Link href={"/"} className="flex items-center justify-center">
          <Image src={logoPng} width={48} height={48} alt="logo" />
          <h1 className="select-none font-head text-2xl">taskord</h1>
        </Link>
        <Sidebar />
      </aside>
      <div className="flex flex-1 flex-col gap-4 overflow-y-auto bg-[#141414] px-6 py-5">
        <Header />
        {children}
      </div>
    </div>
  );
}
