import AuthProvider from "@/src/components/providers/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/src/components/providers/ThemeProvider";
import { cn } from "@/src/utils/styles.utils";
import localFont from "next/font/local";

const eUkraine = localFont({
  src: [
    {
      path: "../../public/static/fonts/e-Ukraine-Thin.otf",
      weight: "100",
    },
    {
      path: "../../public/static/fonts/e-Ukraine-UltraLight.otf",
      weight: "300",
    },
    {
      path: "../../public/static/fonts/e-Ukraine-Light.otf",
      weight: "400",
    },
    {
      path: "../../public/static/fonts/e-Ukraine-Regular.otf",
      weight: "500",
    },
    {
      path: "../../public/static/fonts/e-Ukraine-Medium.otf",
      weight: "600",
    },
    {
      path: "../../public/static/fonts/e-Ukraine-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-e-ukraine",
});

const eUkraineHead = localFont({
  src: [
    {
      path: "../../public/static/fonts/e-UkraineHead-LOGO.otf",
    },
  ],
  variable: "--font-e-ukraine-head",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/static/icons/logo.svg",
  },
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(eUkraine.variable, eUkraineHead.variable, "min-h-screen")}
      >
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            {children}
            {modal}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
