on: [push]
name: Build and deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build release
        run: |
            cargo build --release --all-features

      - name: Deploy to Shuttle
        run: |
          cargo shuttle deploy
        env:
          SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
