on: [ push ]
name: Build and deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd backend
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: goto-bus-stop/setup-zig@v2
      - run: cargo install cargo-zigbuild
      - run: cargo zigbuild --release --target x86_64-unknown-linux-gnu
  deploy_to_fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
